substitutions:
  device_name: "heating-relay"

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml


esphome:
  name: ${device_name}
  comment: WiFi controlled relay powered by ESP
  on_boot:
      - switch.turn_off:
          id: heating_relay

esp8266:
  board: esp01_1m

switch:
  - platform: gpio
    pin: GPIO2
    id: heating_relay
    name: "Turn on heating"
    icon: "mdi:water-heater"
    inverted: true
    