substitutions:
  device_name: "irrigation-node"

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

esphome:
  name: ${device_name}
  friendly_name: ${device_name}

sprinkler:
  - id: sprinkler_ctrlr
    main_switch: "Run Watering"
    auto_advance_switch: "Sprinklers Auto Advance"
    reverse_switch: "Sprinklers Reverse"
    valve_open_delay: 1s
    valves:
      - valve_switch: "Sprinklers - zone 1"
        enable_switch: "Enable zone 1"
        pump_switch_id: sprinkler_pump_sw
        run_duration: 5s
        valve_switch_id: lawn_sprinkler_valve_sw0
      - valve_switch: "Sprinklers - zone 2"
        enable_switch: "Enable zone 2"
        pump_switch_id: sprinkler_pump_sw
        run_duration: 5s
        valve_switch_id: lawn_sprinkler_valve_sw1
      - valve_switch: "Sprinklers - zone 3"
        enable_switch: "Enable zone 3"
        pump_switch_id: sprinkler_pump_sw
        run_duration: 5s
        valve_switch_id: lawn_sprinkler_valve_sw2
      - valve_switch: "Sprinklers - zone 4"
        enable_switch: "Enable zone 4"
        pump_switch_id: sprinkler_pump_sw
        run_duration: 5s
        valve_switch_id: lawn_sprinkler_valve_sw3
      - valve_switch: "Dripline"
        enable_switch: "Enable drip line"
        pump_switch_id: sprinkler_pump_sw
        run_duration: 5s
        valve_switch_id: lawn_sprinkler_valve_sw4

esp8266:
  board: esp01_1m


sensor:
  - platform: dht
    pin: GPIO12
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s

switch:
  - platform: gpio
    id: lawn_sprinkler_valve_sw0
    pin: GPIO16
    inverted: true

  - platform: gpio
    id: lawn_sprinkler_valve_sw1
    pin: GPIO5
    inverted: true

  - platform: gpio
    id: lawn_sprinkler_valve_sw2
    pin: GPIO4
    inverted: true

  - platform: gpio
    id: lawn_sprinkler_valve_sw3
    pin: GPIO0
    inverted: true

  - platform: gpio
    id: lawn_sprinkler_valve_sw4
    pin: GPIO14
    inverted: true

  - platform: gpio
    id: sprinkler_pump_sw
    pin: GPIO2
    inverted: True
